---
title: "Mutation analysis of BCRs from old and young influenza vaccinnees"
author: "Prasida Holla"
date: "2025-02-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This dataset comes from this paper
<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3699344/>

and SRA accession number SRA058972

#Load packages
```{r load packages, include=TRUE, message=FALSE, warning=FALSE}
library(alakazam)
library(igraph)
library(googledrive)
library(shazam)
library(tidyverse)
library(scales)
library(ggrepel)
library(seqinr)
library(Biostrings)
library(ggseqlogo)
```

# import sequences
```{r import seqeuences, include=TRUE, message=FALSE}
temp<- tempfile(fileext = ".rds")
dl <- drive_download(
as_id("1ikz2SZPmktoHU0Dy7zpzXc9-h_a9tmW7"), path = temp, overwrite = TRUE)
all.seq  <-readRDS(file = dl$local_path)

all_files<-bind_rows(all.seq, .id="subject")
```

# Perform mutation analysis on all the sequences
```{r}
#Overall mutations: seperated by replaement an substitution
all_files<- observedMutations(all_files, sequenceColumn="sequence_alignment",
                         germlineColumn="germline_alignment_d_mask",
                         regionDefinition=NULL, 
                         frequency=T,combine = F,
                         nproc=1)

#Overall mutations: unseparated
all_files<- observedMutations(all_files, sequenceColumn="sequence_alignment",
                         germlineColumn="germline_alignment_d_mask",
                         regionDefinition=NULL, 
                         frequency=T,combine = T,
                         nproc=1)

# per region mutations
## clean up mismatches between germline and query sequences
all_files<- data.frame(lapply(all_files, as.character), stringsAsFactors=FALSE)
x<-data.frame(nchar(all_files$sequence_alignment))
y<-data.frame(nchar(all_files$germline_alignment_d_mask))
z<-cbind(x,y)
a<-subset(z, z$nchar.all_files.sequence_alignment.!=z$nchar.all_files.germline_alignment_d_mask.)
# and get the row numberss that have this discrepency, and remove them
all_files<-subset(all_files, !rownames(all_files)%in%rownames(a))

all_files<- observedMutations(all_files, sequenceColumn="sequence_alignment",
                         germlineColumn="germline_alignment_d_mask",
                         regionDefinition=IMGT_V_BY_REGIONS,
                         frequency=T,combine = F,
                         nproc=1)

all_files<- observedMutations(all_files, sequenceColumn="sequence_alignment",
                         germlineColumn="germline_alignment_d_mask",
                         regionDefinition=IMGT_V_BY_CODONS,
                         frequency=T,combine = F,
                         nproc=1)

# add single, r+s values for each mutation freq by region/ codon
all_files$mu_freq_2<-all_files$mu_freq_2_r+all_files$mu_freq_2_s
all_files$mu_freq_1<-all_files$mu_freq_1_r+all_files$mu_freq_1_s
all_files$mu_freq_3<-all_files$mu_freq_3_r+all_files$mu_freq_3_s
all_files$mu_freq_4<-all_files$mu_freq_4_r+all_files$mu_freq_4_s
all_files$mu_freq_5<-all_files$mu_freq_5_r+all_files$mu_freq_5_s
all_files$mu_freq_6<-all_files$mu_freq_6_r+all_files$mu_freq_6_s
all_files$mu_freq_7<-all_files$mu_freq_7_r+all_files$mu_freq_7_s
all_files$mu_freq_8<-all_files$mu_freq_8_r+all_files$mu_freq_8_s
all_files$mu_freq_9<-all_files$mu_freq_9_r+all_files$mu_freq_9_s
all_files$mu_freq_10<-all_files$mu_freq_10_r+all_files$mu_freq_10_s
all_files$mu_freq_11<-all_files$mu_freq_11_r+all_files$mu_freq_11_s
all_files$mu_freq_12<-all_files$mu_freq_12_r+all_files$mu_freq_12_s
all_files$mu_freq_13<-all_files$mu_freq_13_r+all_files$mu_freq_13_s
all_files$mu_freq_14<-all_files$mu_freq_14_r+all_files$mu_freq_14_s
all_files$mu_freq_15<-all_files$mu_freq_15_r+all_files$mu_freq_15_s
all_files$mu_freq_16<-all_files$mu_freq_16_r+all_files$mu_freq_16_s
all_files$mu_freq_17<-all_files$mu_freq_17_r+all_files$mu_freq_17_s
all_files$mu_freq_18<-all_files$mu_freq_18_r+all_files$mu_freq_18_s
all_files$mu_freq_19<-all_files$mu_freq_19_r+all_files$mu_freq_19_s
all_files$mu_freq_20<-all_files$mu_freq_20_r+all_files$mu_freq_20_s
all_files$mu_freq_21<-all_files$mu_freq_21_r+all_files$mu_freq_21_s
all_files$mu_freq_22<-all_files$mu_freq_22_r+all_files$mu_freq_22_s
all_files$mu_freq_23<-all_files$mu_freq_23_r+all_files$mu_freq_23_s
all_files$mu_freq_24<-all_files$mu_freq_24_r+all_files$mu_freq_24_s
all_files$mu_freq_25<-all_files$mu_freq_25_r+all_files$mu_freq_25_s
all_files$mu_freq_26<-all_files$mu_freq_26_r+all_files$mu_freq_26_s
all_files$mu_freq_27<-all_files$mu_freq_27_r+all_files$mu_freq_27_s
all_files$mu_freq_28<-all_files$mu_freq_28_r+all_files$mu_freq_28_s
all_files$mu_freq_29<-all_files$mu_freq_29_r+all_files$mu_freq_29_s
all_files$mu_freq_30<-all_files$mu_freq_30_r+all_files$mu_freq_30_s
all_files$mu_freq_31<-all_files$mu_freq_31_r+all_files$mu_freq_31_s
all_files$mu_freq_32<-all_files$mu_freq_32_r+all_files$mu_freq_32_s
all_files$mu_freq_33<-all_files$mu_freq_33_r+all_files$mu_freq_33_s
all_files$mu_freq_34<-all_files$mu_freq_34_r+all_files$mu_freq_34_s
all_files$mu_freq_35<-all_files$mu_freq_35_r+all_files$mu_freq_35_s
all_files$mu_freq_36<-all_files$mu_freq_36_r+all_files$mu_freq_36_s
all_files$mu_freq_37<-all_files$mu_freq_37_r+all_files$mu_freq_37_s
all_files$mu_freq_38<-all_files$mu_freq_38_r+all_files$mu_freq_38_s
all_files$mu_freq_39<-all_files$mu_freq_39_r+all_files$mu_freq_39_s
all_files$mu_freq_40<-all_files$mu_freq_40_r+all_files$mu_freq_40_s
all_files$mu_freq_41<-all_files$mu_freq_41_r+all_files$mu_freq_41_s
all_files$mu_freq_42<-all_files$mu_freq_42_r+all_files$mu_freq_42_s
all_files$mu_freq_43<-all_files$mu_freq_43_r+all_files$mu_freq_43_s
all_files$mu_freq_44<-all_files$mu_freq_44_r+all_files$mu_freq_44_s
all_files$mu_freq_45<-all_files$mu_freq_45_r+all_files$mu_freq_45_s
all_files$mu_freq_46<-all_files$mu_freq_46_r+all_files$mu_freq_46_s
all_files$mu_freq_47<-all_files$mu_freq_47_r+all_files$mu_freq_47_s
all_files$mu_freq_48<-all_files$mu_freq_48_r+all_files$mu_freq_48_s
all_files$mu_freq_49<-all_files$mu_freq_49_r+all_files$mu_freq_49_s
all_files$mu_freq_50<-all_files$mu_freq_50_r+all_files$mu_freq_50_s
all_files$mu_freq_51<-all_files$mu_freq_51_r+all_files$mu_freq_51_s
all_files$mu_freq_52<-all_files$mu_freq_52_r+all_files$mu_freq_52_s
all_files$mu_freq_53<-all_files$mu_freq_53_r+all_files$mu_freq_53_s
all_files$mu_freq_54<-all_files$mu_freq_54_r+all_files$mu_freq_54_s
all_files$mu_freq_55<-all_files$mu_freq_55_r+all_files$mu_freq_55_s
all_files$mu_freq_56<-all_files$mu_freq_56_r+all_files$mu_freq_56_s
all_files$mu_freq_57<-all_files$mu_freq_57_r+all_files$mu_freq_57_s
all_files$mu_freq_58<-all_files$mu_freq_58_r+all_files$mu_freq_58_s
all_files$mu_freq_59<-all_files$mu_freq_59_r+all_files$mu_freq_59_s
all_files$mu_freq_60<-all_files$mu_freq_60_r+all_files$mu_freq_60_s
all_files$mu_freq_61<-all_files$mu_freq_61_r+all_files$mu_freq_61_s
all_files$mu_freq_62<-all_files$mu_freq_62_r+all_files$mu_freq_62_s
all_files$mu_freq_63<-all_files$mu_freq_63_r+all_files$mu_freq_63_s
all_files$mu_freq_64<-all_files$mu_freq_64_r+all_files$mu_freq_64_s
all_files$mu_freq_65<-all_files$mu_freq_65_r+all_files$mu_freq_65_s
all_files$mu_freq_66<-all_files$mu_freq_66_r+all_files$mu_freq_66_s
all_files$mu_freq_67<-all_files$mu_freq_67_r+all_files$mu_freq_67_s
all_files$mu_freq_68<-all_files$mu_freq_68_r+all_files$mu_freq_68_s
all_files$mu_freq_69<-all_files$mu_freq_69_r+all_files$mu_freq_69_s
all_files$mu_freq_70<-all_files$mu_freq_70_r+all_files$mu_freq_70_s
all_files$mu_freq_71<-all_files$mu_freq_71_r+all_files$mu_freq_71_s
all_files$mu_freq_72<-all_files$mu_freq_72_r+all_files$mu_freq_72_s
all_files$mu_freq_73<-all_files$mu_freq_73_r+all_files$mu_freq_73_s
all_files$mu_freq_74<-all_files$mu_freq_74_r+all_files$mu_freq_74_s
all_files$mu_freq_75<-all_files$mu_freq_75_r+all_files$mu_freq_75_s
all_files$mu_freq_76<-all_files$mu_freq_76_r+all_files$mu_freq_76_s
all_files$mu_freq_77<-all_files$mu_freq_77_r+all_files$mu_freq_77_s
all_files$mu_freq_78<-all_files$mu_freq_78_r+all_files$mu_freq_78_s
all_files$mu_freq_79<-all_files$mu_freq_79_r+all_files$mu_freq_79_s
all_files$mu_freq_80<-all_files$mu_freq_80_r+all_files$mu_freq_80_s
all_files$mu_freq_81<-all_files$mu_freq_81_r+all_files$mu_freq_81_s
all_files$mu_freq_82<-all_files$mu_freq_82_r+all_files$mu_freq_82_s
all_files$mu_freq_83<-all_files$mu_freq_83_r+all_files$mu_freq_83_s
all_files$mu_freq_84<-all_files$mu_freq_84_r+all_files$mu_freq_84_s
all_files$mu_freq_85<-all_files$mu_freq_85_r+all_files$mu_freq_85_s
all_files$mu_freq_86<-all_files$mu_freq_86_r+all_files$mu_freq_86_s
all_files$mu_freq_87<-all_files$mu_freq_87_r+all_files$mu_freq_87_s
all_files$mu_freq_88<-all_files$mu_freq_88_r+all_files$mu_freq_88_s
all_files$mu_freq_89<-all_files$mu_freq_89_r+all_files$mu_freq_89_s
all_files$mu_freq_90<-all_files$mu_freq_90_r+all_files$mu_freq_90_s
all_files$mu_freq_91<-all_files$mu_freq_91_r+all_files$mu_freq_91_s
all_files$mu_freq_92<-all_files$mu_freq_92_r+all_files$mu_freq_92_s
all_files$mu_freq_93<-all_files$mu_freq_93_r+all_files$mu_freq_93_s
all_files$mu_freq_94<-all_files$mu_freq_94_r+all_files$mu_freq_94_s
all_files$mu_freq_95<-all_files$mu_freq_95_r+all_files$mu_freq_95_s
all_files$mu_freq_96<-all_files$mu_freq_96_r+all_files$mu_freq_96_s
all_files$mu_freq_97<-all_files$mu_freq_97_r+all_files$mu_freq_97_s
all_files$mu_freq_98<-all_files$mu_freq_98_r+all_files$mu_freq_98_s
all_files$mu_freq_99<-all_files$mu_freq_99_r+all_files$mu_freq_99_s
all_files$mu_freq_100<-all_files$mu_freq_100_r+all_files$mu_freq_100_s
all_files$mu_freq_101<-all_files$mu_freq_101_r+all_files$mu_freq_101_s
all_files$mu_freq_102<-all_files$mu_freq_102_r+all_files$mu_freq_102_s
all_files$mu_freq_103<-all_files$mu_freq_103_r+all_files$mu_freq_103_s
all_files$mu_freq_104<-all_files$mu_freq_104_r+all_files$mu_freq_104_s

all_files$mu_freq_fwr1<-all_files$mu_freq_fwr1_r+all_files$mu_freq_fwr1_s
all_files$mu_freq_fwr2<-all_files$mu_freq_fwr2_r+all_files$mu_freq_fwr2_s
all_files$mu_freq_fwr3<-all_files$mu_freq_fwr3_r+all_files$mu_freq_fwr3_s
all_files$mu_freq_cdr1<-all_files$mu_freq_cdr1_r+all_files$mu_freq_cdr1_s
all_files$mu_freq_cdr2<-all_files$mu_freq_cdr2_r+all_files$mu_freq_cdr2_s

# remove _r and _s columns from individual codon mutation analysis for clarity
all_files<-all_files[, -c(67:284)]

#Subset IGHV4-34
allv434<-all_files[grep("IGHV4-34", all_files$v_call),]
```

